import bleach

# Define the HTML policy for artifact rendering
ALLOWED_TAGS = [
    'h1', 'h2', 'h3', 'h4', 'h5', 'h6',
    'p', 'a', 'ul', 'ol', 'li', 'b', 'i', 'strong', 'em', 'strike',
    'code', 'pre', 'hr', 'br', 'div', 'span', 'blockquote',
    'table', 'thead', 'tbody', 'tr', 'th', 'td',
    'style' # Allow inline styles for self-contained artifacts
]

ALLOWED_ATTRIBUTES = {
    '*': ['class', 'id', 'style'],
    'a': ['href', 'title', 'target'],
    'img': ['src', 'alt', 'title']
}

ALLOWED_STYLES = [
    'color', 'background-color', 'font-family', 'font-size', 'font-weight',
    'text-align', 'margin', 'padding', 'border', 'display', 'flex', 'grid'
]

def sanitize_html(html_content: str) -> str:
    """
    Sanitizes untrusted HTML content generated by the LLM.
    Blocks <script>, <iframe>, and event handlers to prevent XSS.
    Allows basic structural and styling tags.
    """
    return bleach.clean(
        html_content,
        tags=ALLOWED_TAGS,
        attributes=ALLOWED_ATTRIBUTES,
        styles=ALLOWED_STYLES,
        strip=True
    )
